version: '3.8'

services:
  # Node.js 應用程式
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=smartconstruction123
      - DB_NAME=smart_construction
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs

  # MySQL 資料庫
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=smartconstruction123
      - MYSQL_DATABASE=smart_construction
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Redis 快取
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  mysql_data: